steps:
  # Build and push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'REACT_APP_BACKEND_URL=${_BACKEND_URL}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/vegsoft-solutions:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/vegsoft-solutions:latest'
      - '.'

  # Push image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/vegsoft-solutions:$COMMIT_SHA']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/vegsoft-solutions:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'vegsoft-solutions'
      - '--image'
      - 'gcr.io/$PROJECT_ID/vegsoft-solutions:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--service-account'
      - 'vegsoft-backend-emergent@vegsoft-solutions-prod.iam.gserviceaccount.com'
      - '--set-env-vars'
      - 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID,CALENDAR_ID=c_01b41f98727a6c0471d08505dcf0cc11ec00229b2a2478f97e8b79c1f457a1e0@group.calendar.google.com,FRONTEND_URL=${_BACKEND_URL}'

substitutions:
  _BACKEND_URL: 'https://vegsoft-solutions-307650209341.us-central1.run.app'

images:
  - 'gcr.io/$PROJECT_ID/vegsoft-solutions:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/vegsoft-solutions:latest'

options:
  logging: CLOUD_LOGGING_ONLY
